### ISSUE TITLE
输入示例问题

### ISSUE THREAD

**Issue by Lezsin** [wenke727/ST-MapMatching#12]
在对`./data/trajs`文件夹下的 geojson 文件进行一一测试时，我发现只有极少的几个能够得到匹配结果，其余的都会报错。
如将 demo.py 文件中第 21 行的 idx 参数修改为 0，对应的 traj_0.geojson 并不能成功匹配，报错如下：
```
Traceback (most recent call last):
  File "/home/jwx/Code/Python/wenke727_ST-Matching_205/demo.py", line 23, in <module>
    res = matcher.matching(traj, top_k=5, dir_trans=True, details=False, plot=True,
  File "/home/jwx/Code/Python/wenke727_ST-Matching_205/mapmatching/utils/timer.py", line 36, in inner
    res = func(*args, **kwargs)
  File "/home/jwx/Code/Python/wenke727_ST-Matching_205/mapmatching/matching.py", line 87, in matching
    cands = analyse_geometric_info(_traj, self.base_edges, top_k, self.cand_search_radius)
  File "/home/jwx/Code/Python/wenke727_ST-Matching_205/mapmatching/match/geometricAnalysis.py", line 41, in analyse_geometric_info
    cands.loc[:, 'observ_prob'] = cal_observ_prob(cands.dist_p2c)
AttributeError: 'NoneType' object has no attribute 'dist_p2c'
```
请问我该如何修改输入示例呢？

**Comment by wenke727** [comment]
提供的预处理路网仅覆盖深圳南山区万科云城片区，并没有完成覆盖`./data/trajs`中所有的测试用例。 若需测试所有用例，需自行调整 bbox 获取相应区域的路网。
下个版本将增加边界判断逻辑。

**Comment by Lezsin** [comment]
明白了，感谢您的回复！
另外，假如要对其他城市进行地图匹配，除了修改 bbox 指定的范围和准备对应区域的轨迹点以外，还需要对代码进行额外的修改吗？

**Comment by wenke727** [comment]
应该是可以的，若有问题，欢迎反馈。

**Comment by wenke727** [comment]
V2.0.6 已增加路网是否覆盖轨迹的逻辑判断。

**Comment by Lezsin** [comment]
在对`traj_9.geojson`进行测试的过程中，我多次调整bbox的范围，都提示“AssertionError: check the bbox contained the trajectory or not”，请问这是什么原因呢？

**Comment by Lezsin** [comment]
在测试第15条轨迹时，我调整了bbox的范围，出现了如下报错：

> Traceback (most recent call last):
>   File "/home/jwx/Code/Python/ST-Matching_206/demo.py", line 15, in <module>
>     net = build_geograph(bbox=[113.9164, 22.5242, 113.9395, 22.5781],
>   File "/home/jwx/Code/Python/ST-Matching_206/mapmatching/osmnet/build_graph.py", line 44, in build_geograph
>     df_nodes, df_edges, df_ways = parse_xml_to_graph(xml_fn, *args, **kwargs)
>   File "/home/jwx/Code/Python/ST-Matching_206/mapmatching/osmnet/parse_osm_xml.py", line 363, in parse_xml_to_graph
>     df_edges = _process_multi_edges(df_edges, ori_df_edges, df_ways)
>   File "/home/jwx/Code/Python/ST-Matching_206/mapmatching/osmnet/parse_osm_xml.py", line 334, in _process_multi_edges
>     neg_df_edges.loc[:, 'dir'] = -1
>   File "/home/jwx/miniconda3/envs/ST-Matching/lib/python3.9/site-packages/pandas/core/indexing.py", line 818, in __setitem__
>     iloc._setitem_with_indexer(indexer, value, self.name)
>   File "/home/jwx/miniconda3/envs/ST-Matching/lib/python3.9/site-packages/pandas/core/indexing.py", line 1718, in _setitem_with_indexer
>     raise ValueError(
> ValueError: cannot set a frame with no defined index and a scalar

我注意到这个报错和之前的一个 issue #11 类似，您提到在版本 V2.0.5 中已增加对空 Dataframe 边界条件的处理，但在 V2.0.6 仍然出现了同样的报错。您对此有什么建议吗？

**Comment by wenke727** [comment]
可能小范围的路网处理还有一些边界条件没有考虑到，会有一些 bug。我之前测试是先预处理好整个深圳市路网的数据，然后再在所有的轨迹上测试。晚点排查下原因

**Comment by wenke727** [comment]
错误在 [V2.0.7](https://github.com/wenke727/ST-MapMatching/tree/78a066e5692a2346879ff0d26666d2b1a37947c4) 得以修复
