### ISSUE TITLE
n_jobs 参数相关

### ISSUE THREAD

**Issue by Lezsin** [wenke727/ST-MapMatching#13]
在 demo.py 中，我尝试对`build_geograph()`函数中的`n_jobs`参数进行修改。由于虚拟机只分配到了 2 个核心，我在 1 和 2 之间进行修改，但`Parse ways`、`Parse nodes`、`Transform to Dataframe`等步骤的时长并没有明显变化，请问是虚拟机的问题吗？还是`n_jobs`参数起作用的地方并不在此？

**Comment by wenke727** [comment]
这几个步骤在代码设计的时候没有考虑多进程处理，因为调用的 `osmium` 库的底层是 C 写的，解析路网文件很快。
多进程主要用于提升瓶颈处的处理速度，主要体现在：1）对路网的压缩，如将出入度均为 1 的节点线段合并；2）将点的 id 序列转成 LineString。

**Comment by Lezsin** [comment]
了解了，谢谢您！
