### ISSUE TITLE
匹配错误

### ISSUE THREAD

**Issue by Lezsin** [wenke727/ST-MapMatching#15]
在使用自己的GPS数据集进行测试时，最终的匹配效果出现了严重的错误，如下所示：
![image](https://github.com/wenke727/ST-MapMatching/assets/121026637/15a4a6cf-a825-4240-9a6c-211ec3587308)
某些地方本可以直接行至下一个采样点，但仍要多绕一段路：
![image](https://github.com/wenke727/ST-MapMatching/assets/121026637/53dc10e6-c1f9-408f-b396-58bd2c9d9b3c)
这是否与道路速度限制的影响因子有关？

**Comment by wenke727** [comment]
提供下 GPS 样例数据，我这边测试下

**Comment by Lezsin** [comment]
[traj_1.txt](https://github.com/wenke727/ST-MapMatching/files/11527530/traj_1.txt)
谢谢您的回复！将后缀改为`.geojson`即可

**Comment by wenke727** [comment]
产生错误几个原因：

- beam search 剪枝算法有误，应该根据全局的概率剪枝，而非局部概率；
- 超参数没设置好，top_k 适当增大，考虑到广州路况复杂，多层立交的情况也比较普遍；search radius 适当增加，因 GPS 偏移较严重；
- 轨迹较长，错误容易累积，上游错误会导致下游匹配错乱。建议可以适当切分轨迹，根据转移概率判断异常区间

错误均在 [V2.0.7](https://github.com/wenke727/ST-MapMatching/tree/78a066e5692a2346879ff0d26666d2b1a37947c4) 得以修复，注意需要将 top_k 和 search_radius 适当增大

```python
res = matcher.matching(traj, top_k=8, search_radius=80)
```
PS: 速度因素尚未参与地图匹配的概率计算中，最后输出的结果仅仅是统计了一个途径路段的加权平均速度（单位 m/s），后续会将会增加速度匹配的逻辑。
