### ISSUE TITLE
改进方向

### ISSUE THREAD

**Issue by Lezsin** [wenke727/ST-MapMatching#16]
请问和原文《[Map-Matching for Low-Sampling-Rate GPS Trajectories](https://www.microsoft.com/en-us/research/publication/map-matching-for-low-sampling-rate-gps-trajectories/)》相比，本项目具体有哪些改动呢？

**Comment by wenke727** [comment]
主要是复现，以及工程上的一些优化细节，大的改动方向谈不上。

在匹配的特征上，除了论文中提到的，还涉及轨迹的方位角。

在流程上，项目是一个端到端的地图匹配，可以自动解析 OSM 路网，然后再进行匹配。

在功能上，提供一些小功能，如：将节点投影到匹配轨迹上；计算轨迹和匹配路径的相似度等。

**Comment by Lezsin** [comment]
明白了，感谢您的回复！
