### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by laozheng1** [wenke727/ST-MapMatching#3]
from DigraphOSM import DigraphOSM
from MapMathing import ST_Matching

请问这两个依赖模块需要安装什么呢

**Comment by wenke727** [comment]
抱歉，目前代码正在重构中，接口有所变化，Readme.md 中的示意代码可在 [V1.0](https://github.com/wenke727/ST-MapMatching/tree/V1.0) 版本复现。
新代码的调用方式将在 V1.2 版本发布。
