### ISSUE TITLE
多进程报错

### ISSUE THREAD

**Issue by Lezsin** [wenke727/ST-MapMatching#7]
请问是否存在一个简单的设置，能够停止调用多进程，以使得代码能够在windows下运行？

**Comment by wenke727** [comment]
可以考虑在下一个小版本中优化。
加入多进程处理的动机是在预处理阶段加速处理城市集群的路网。目前，匹配阶段是没有多进程的。

**Comment by Lezsin** [comment]
非常感谢您的回复！也许您可以考虑提供预处理后的路网数据，并在程序中设置一个读取它的接口。非常惭愧地说，直到今天我都没能跑出一个地图匹配结果的示意图 (T_T) 无论如何，预祝您的项目进展顺利！

**Comment by wenke727** [comment]
抱歉，是抱着学习的态度做的小工具，代码很业余。
我晚些时候更新下深圳南山区的路网，相应的接口是预留了的。
若有其他问题，欢迎进一步交流

**Comment by wenke727** [comment]
已在 V2.0.3 版本，提供 demo.py 脚本所需的预处理路网

**Comment by Lezsin** [comment]
非常感谢您！我已经在尝试针对 V2.0.3 版本配置新环境了（之前在学习 V1.2.7）。
另外，我很想知道您的 shapely 包版本是多少，因为：
1. shapely 所基于的 geos 包版本和 pygeos 所基于的 geos 包版本最好是兼容的，不然会提示：

> UserWarning: The Shapely GEOS version (3.11.1-CAPI-1.17.1) is incompatible with the GEOS version PyGEOS was compiled with (3.10.3-CAPI-1.16.1). Conversions between both will be slow.

2. 我注意到您在 matching.py 文件中开头注释了一句`os.environ["USE_PYGEOS"] = "0"`，这和针对以下错误提供的建议很类似：

> UserWarning: Shapely 2.0 is installed, but because PyGEOS is also installed, GeoPandas will still use PyGEOS by default for now. To force to use and test Shapely 2.0, you have to set the environment variable USE_PYGEOS=0. You can do this before starting the Python process, or in your code before importing geopandas:
> import os
> os.environ['USE_PYGEOS'] = '0'
> import geopandas

耽误您的时间，再次致歉！

**Comment by Lezsin** [comment]
另：刚才我遇到了新的报错，所以想再问问您的 matplotlib 包版本和 python 版本，谢谢！

**Comment by wenke727** [comment]
详细依赖库详见 `requirement.txt`

1. 由于开发周期内较长，shapely 从 1.0 系列升级到 2.0 系列，geopandas 的部分矢量化操作不再依赖 `pygeos`，可选择不安装，该问题就不存在了。环境安装的方式可参考 readme.md

2. 同一，一开始需要 `pygeos` 的矢量化加速操作加持，故需要设置全局变量，后因 shapely 发布了其颇具里程碑意义的2.0正式版本，为我们带来了更加澎湃的运算性能提升，故注释。为避免误会，在后续版本将删除该行代码。

3. Python 版本为3.9，matplotlib 版本3.6.3。报错的原因是默认没有安装 [Tilemap](https://github.com/wenke727/TileMap) 库导致的，相应的逻辑已在 V2.0.4 更正。[Tilemap](https://github.com/wenke727/TileMap) 主要是解决在实际开发调试中路网可视化效果不佳的痛点，增加卫星瓦片作为底图，使得效果更直观。

**Comment by Lezsin** [comment]
完全了解了！
您耐心的态度和及时的回复令人敬佩 (^o^)
